# Run production build with composer and npm
## If these fail, don't release update
name: Build

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  php:

    runs-on: ubuntu-latest
    strategy:
          matrix:
            php-version: [ 7.2, 7.3, 7.4 ]
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php-version }}
        dev: no
        args: --no-dev --prefer-dist --no-progress
